Repository archesproject/arches-her, pull requests merged in 2024-04, with the labels that each got.

#1090 #1086 Update Static File Loading in Active Consultations
  arches_her/templates/views/components/plugins/active-consultations.htm
Labels: enhancement

#1093 Adds missing configurations to report templates
  arches_her/media/js/views/components/reports/activity.js
  arches_her/media/js/views/components/reports/application-area.js
  arches_her/media/js/views/components/reports/archive-source.js
  arches_her/media/js/views/components/reports/area.js
  arches_her/media/js/views/components/reports/artefact.js
  arches_her/media/js/views/components/reports/bibliographic-source.js
  arches_her/media/js/views/components/reports/consultation.js
  arches_her/media/js/views/components/reports/heritage-story.js
  arches_her/media/js/views/components/reports/historic-aircraft.js
  arches_her/media/js/views/components/reports/historic-landscape-characterization.js
  arches_her/media/js/views/components/reports/maritime-vessel.js
  arches_her/media/js/views/components/reports/monument.js
  arches_her/media/js/views/components/reports/organization.js
  arches_her/media/js/views/components/reports/person.js
Labels: bug

#1095 #1087 Upgrade HTML templates
  arches_her/templates/html_export/076f9381-7b00-11e9-8d6b-80000b44d1d9.htm
  arches_her/templates/html_export/49bac32e-5464-11e9-a6e2-000d3ab1e588.htm
  arches_her/templates/html_export/934cd7f0-480a-11ea-9240-c4d9877d154e.htm
  arches_her/templates/html_export/979aaf0b-7042-11ea-9674-287fcf6a5e72.htm
  arches_her/templates/html_export/b8032b00-594d-11e9-9cf0-18cf5eb368c4.htm
  arches_her/templates/html_export/b9e0701e-5463-11e9-b5f5-000d3ab1e588.htm
Labels: enhancement

#1113 Fix search_overlays.sql loading in package
  arches_her/pkg/preliminary_sql/search_overlays.sql
Labels: bug

#1100 #1099 Add Accessibility Plugin
  arches_her/media/js/views/components/plugins/accessibility.js
  arches_her/pkg/extensions/plugins/accessibility/accessibility.htm
  arches_her/pkg/extensions/plugins/accessibility/accessibility.js
  arches_her/pkg/extensions/plugins/accessibility/accessibility.json
  arches_her/plugins/accessibility.json
  arches_her/templates/views/components/plugins/accessibility.htm
Labels: enhancement

#1114 #1106 Add BNG Search Filter
  arches_her/media/css/bng-filter.css
  arches_her/media/css/project.css
  arches_her/media/js/views/components/search/bng-filter.js
  arches_her/pkg/extensions/css/bng-filter.css
  arches_her/pkg/extensions/search/bng-filter/bng-filter.htm
  arches_her/pkg/extensions/search/bng-filter/bng-filter.js
  arches_her/pkg/extensions/search/bng-filter/bng-filter.py
  arches_her/pkg/preliminary_sql/search_filters.sql
  arches_her/search/components/bng-filter.py
  arches_her/settings.py
  arches_her/templates/views/components/search/bng-filter.htm
Labels: enhancement

#1117 #1094 Remove Stickler Config
  .stickler.yml
Labels: enhancement

#1118 #1109 Add deactivated spatial views
  arches_her/pkg/post_sql/create_spatial_views.sql
Labels: enhancement

#1122 Initial fixes for Workflows
  arches_her/media/js/models/card-widget.js
  arches_her/media/js/utils/workflows.js
  arches_her/media/js/views/components/plugins/application-area.js
  arches_her/media/js/views/components/plugins/communication-workflow.js
  arches_her/media/js/views/components/plugins/consultation-workflow.js
  arches_her/media/js/views/components/plugins/correspondence-workflow.js
  arches_her/media/js/views/components/plugins/site-visit.js
  arches_her/media/js/views/components/workflows/application-area/app-area-address-step.js
  arches_her/media/js/views/components/workflows/application-area/app-area-final-step.js
  arches_her/media/js/views/components/workflows/communication-workflow/communication-select-resource.js
  arches_her/media/js/views/components/workflows/consultation/consultation-map-step.js
  arches_her/media/js/views/components/workflows/consultation/consultations-final-step.js
  arches_her/media/js/views/components/workflows/correspondence-letter-step.js
  arches_her/media/js/views/components/workflows/file-template.js
  arches_her/media/js/views/components/workflows/photo-gallery-step.js
  arches_her/media/js/views/components/workflows/select-resource-step.js
  arches_her/media/js/views/components/workflows/site-visit/site-visit-final-step.js
  arches_her/media/js/views/components/workflows/summary-step.js
Labels: bug, enhancement

#1130 Fixes Consultation workflow
  arches_her/media/js/utils/workflows.js
  arches_her/media/js/views/components/workflows/consultation/consultation-dates-step.js
Labels: Workflow: Consultations

#1136 #1123 Communication Workflow Upgrade
  arches_her/media/js/views/components/plugins/communication-workflow.js
  arches_her/media/js/views/components/workflows/communication-workflow/communication-select-resource.js
  arches_her/templates/views/components/workflows/communication-workflow/communication-select-resource.htm
Labels: Workflow: Communication

#1138 #1108 Update README
  README.md
  README.txt
Labels: enhancement

#1148 #1140 Change onkeyup attribute to new functions in reports
  arches_her/media/js/views/components/reports/bibliographic-source.js
  arches_her/media/js/views/components/reports/scenes/contact.js
  arches_her/templates/views/components/reports/activity.htm
  arches_her/templates/views/components/reports/application-area.htm
  arches_her/templates/views/components/reports/archive-source.htm
  arches_her/templates/views/components/reports/area.htm
  arches_her/templates/views/components/reports/artefact.htm
  arches_her/templates/views/components/reports/bibliographic-source.htm
  arches_her/templates/views/components/reports/consultation.htm
  arches_her/templates/views/components/reports/digital-object.htm
  arches_her/templates/views/components/reports/heritage-story.htm
  arches_her/templates/views/components/reports/historic-aircraft.htm
  arches_her/templates/views/components/reports/historic-landscape-characterization.htm
  arches_her/templates/views/components/reports/maritime-vessel.htm
  arches_her/templates/views/components/reports/monument.htm
  arches_her/templates/views/components/reports/organization.htm
  arches_her/templates/views/components/reports/period.htm
  arches_her/templates/views/components/reports/person.htm
  arches_her/templates/views/components/reports/place.htm
  arches_her/templates/views/components/reports/scenes/archive.htm
  arches_her/templates/views/components/reports/scenes/assessments.htm
  arches_her/templates/views/components/reports/scenes/audit.htm
  arches_her/templates/views/components/reports/scenes/classifications.htm
  arches_her/templates/views/components/reports/scenes/contact.htm
  arches_her/templates/views/components/reports/scenes/copyright.htm
  arches_her/templates/views/components/reports/scenes/default.htm
  arches_her/templates/views/components/reports/scenes/description.htm
  arches_her/templates/views/components/reports/scenes/images.htm
  arches_her/templates/views/components/reports/scenes/json.htm
  arches_her/templates/views/components/reports/scenes/location.htm
  arches_her/templates/views/components/reports/scenes/name.htm
  arches_her/templates/views/components/reports/scenes/people.htm
  arches_her/templates/views/components/reports/scenes/protection.htm
  arches_her/templates/views/components/reports/scenes/referenced-by.htm
  arches_her/templates/views/components/reports/scenes/resources.htm
Labels: Subject: Accessibility

#1152 #1150 Missing href="#"
  arches_her/templates/views/components/reports/activity.htm
  arches_her/templates/views/components/reports/application-area.htm
  arches_her/templates/views/components/reports/bibliographic-source.htm
  arches_her/templates/views/components/reports/consultation.htm
  arches_her/templates/views/components/reports/historic-landscape-characterization.htm
  arches_her/templates/views/components/reports/scenes/archive.htm
  arches_her/templates/views/components/reports/scenes/assessments.htm
  arches_her/templates/views/components/reports/scenes/classifications.htm
  arches_her/templates/views/components/reports/scenes/description.htm
  arches_her/templates/views/components/reports/scenes/images.htm
  arches_her/templates/views/components/reports/scenes/location.htm
  arches_her/templates/views/components/reports/scenes/name.htm
  arches_her/templates/views/components/reports/scenes/people.htm
  arches_her/templates/views/components/reports/scenes/protection.htm
Labels: Subject: Accessibility

#1139 #1134 Resource Descriptors removed
  arches_her/urls.py
  arches_her/views/resource.py
Labels: bug

#1154 Adds hotfix for string and resource instance labelling in spatial views due to internationalisation
  arches_her/pkg/post_sql/spatial_views_intl_hotfix.sql
Labels: bug

#1158 Fix add communication button
  arches_her/templates/views/components/reports/consultation.htm
Labels: bug

#1115 #1102 Creates unique filename for letter using time as suffix
  arches_her/views/file_template.py
Labels: bug
