Repository archesproject/arches-her, pull requests merged in 2024-07, with the labels that each got.

#1235 Add skip to content to index page
  arches_her/media/css/_project-variables.scss
  arches_her/media/css/project.scss
  arches_her/templates/index.htm
Labels: enhancement

#1239 #1233 Download ready link moved outside check for files
  arches_her/templates/email/download_ready_email_notification.htm
Labels: bug

#1244 Update docker files to support development in containers
  README.md
  docker/arches_her/Dockerfile
  docker/arches_her/docker-compose-dependencies.yml
  docker/arches_her/docker-compose-persist-dependencies.yml
  docker/arches_her/docker-compose.yml
  docker/arches_her/docker/conf.d/celerybeat.conf
  docker/arches_her/docker/conf.d/celeryd.conf
  docker/arches_her/docker/entrypoint.sh
  docker/arches_her/docker/env_file.env
  docker/arches_her/docker/init-unix.sql
  docker/arches_her/docker/nginx-config/default.conf
  docker/arches_her/docker/nginx-config/default_with_pg_serv.conf
  docker/arches_her/docker/pg_featureserv_config/pg_featureserv.toml
  docker/arches_her/docker/pg_tileserv_config/pg_tileserv.toml
  docker/arches_her/docker/settings_local.py
  docker/arches_her/docker/supervisor.conf
  docker/arches_her/docker_down.bat
  docker/arches_her/docker_up.bat
  docker/env_file.env
  docker/settings_local.py
Labels: enhancement

#1268 Fixes contrast issue for codemirror in aher tabbed reports
  arches_her/media/css/report_templates.css
Labels: Subject: Accessibility

#1228 Add Record Type node to Monument and Area graphs
  arches_her/pkg/graphs/branches/Record Type.json
  arches_her/pkg/graphs/resource_models/Area.json
  arches_her/pkg/graphs/resource_models/Monument.json
Labels: modelling

#1275 #1274 Remove console.log causing issues with scene rendering
  arches_her/media/js/views/components/reports/scenes/location.js
Labels: bug

#1269 #1264 Aria Label and Empty Link Accessibility Errors
  arches_her/media/js/utils/report.js
  arches_her/templates/views/components/reports/activity.htm
  arches_her/templates/views/components/reports/scenes/location.htm
  arches_her/templates/views/components/reports/scenes/name.htm
  arches_her/templates/views/components/reports/scenes/people.htm
Labels: bug, Subject: Accessibility

#1195 Change Area Land Use Classification nodegroup cardinality
  arches_her/pkg/graphs/resource_models/Area.json
Labels: modelling

#1230 Add N/A value to SHINE Significance
  arches_her/pkg/graphs/branches/Area.json
  arches_her/pkg/graphs/branches/Location Data.json
  arches_her/pkg/graphs/resource_models/Activity.json
  arches_her/pkg/graphs/resource_models/Area.json
  arches_her/pkg/graphs/resource_models/Artefact.json
  arches_her/pkg/graphs/resource_models/Historic Aircraft.json
  arches_her/pkg/graphs/resource_models/Maritime Vessel.json
  arches_her/pkg/graphs/resource_models/Monument.json
Labels: modelling

#1283 Add Advice Start Date and End Date as columns to Consultation Advice table
  arches_her/media/js/views/components/reports/consultation.js
  arches_her/templates/views/components/reports/consultation.htm
Labels: enhancement

#1284 Remove height css as no longer required AB#70013
  arches_her/media/css/project.css
Labels: bug
